site_name: Documentation Econum

nav:
  - Accueil: index.md
  - Rapport: rapport.md
  - Frontend: frontend.md
  - Backend: backend.md
  - Notebook de test: notebook.md
  - Recommandations: recommandations.md

theme: readthedocs